version: '3'
services:
  realworld-app:
    container_name: realworld
    image: ruby:2.4
    working_dir: /app
    environment:
      - BUNDLE_PATH=/app/bundle
    volumes:
      - .:/app
    ports:
      - 3000:3000
    entrypoint: /app/scripts/start
